### PR TITLE
Fixes memory leak and reference release issues...

### LINKED ISSUE #102: Is this potential memleak if Persistent's Reset is not called
The generated NanXXX class may contain Persistent handle, and the destructor does't call the Reset() method for the handle, and rely on the Persistent::~Persistent() to release the content, That may have potential memleak as whether the ~Persistent() free the resources depends on its traits's flags.

### LINKED ISSUE #103: Potential memleak if BorrowXXXImpl method called
In ./nanCxxHeader.dot, line 45:
The borrow method just overwrite the old impl_ without check to free it.
`impl_ = newObj; owns_impl_ = false;`

Though this class aims to borrow the ownership, but when the NanXXX instance is created, a default impl is created and assigned to impl_, thus, the impl_ shall be freed.

### PR DESCRIPTION
**Pull request by kenny-y**
Closes #102
Closes #103

### CODE REVIEW

**Comment by kenny-y** [comment]
@tingshao PTAL

File: test/test-event-emitter.js [hunk 1]
```diff
@@ -63,7 +63,7 @@ describe('widl-nan Unit Test - IDL EventEmitter', function() {
     });
   });
 
-  it('Return type of stop() is a Promise', done => {
+  it('Return type of stop() is a Promise', () => {
```
Comment (kenny-y) [inline test/test-event-emitter.js]: When running this test case as single test-suite by `mocha` command, it will timeout.

**Comment by tingshao** [comment]
Merge it.
